version: '3.7'

services:
  mysql_test:
    image: mysql:${MYSQL_VERSION:-latest}
    command: mysqld --user=root --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - "3310:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Password%34
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii
      MYSQL_PASSWORD: Password%34
    container_name: mysql_test

  php-fpm_test:
    container_name: php-fpm_test
    build:
      context: ./php-fpm
    depends_on:
      - mysql_test
    volumes:
      - ./../src/:/var/www

  nginx_test:
    container_name: nginx_test
    build:
      context: ./nginx
    volumes:
      - ./../src/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm_test
    ports:
      - "80:80"
      - "443:443"
volumes:
  data:
